######
# Drupal 8 1.5
# @link https://docs.devwithlando.io/tutorials/drupal8.html
######


# Name
name: APPNAME


# Recipe used
recipe: drupal8
config:
  webroot: .
  php: '7.3'
  via: apache
  database: mariadb
  xdebug: false


# Commands on events
events:
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cr -y
    


# Access
proxy:
  appserver:
    - APPNAME.lndo.site
  mailhog:
    - mail.APPNAME.lndo.site
  pma:
    - pma.APPNAME.lndo.site


# Additional services
services:
  appserver:
    build:
      - composer install
    composer:
      deployer/deployer: '6.*'
  node:
    type: node:11
    globals:
      gulp-cli: "latest"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  pma:
    type: phpmyadmin


# Additionnal commands line "lando XXX"
tooling:
  drush:
    cmd: /app/vendor/bin/drush
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
  gulp:
    service: node
  dep:
    service: appserver
    description: "Deploy app with deploy.php"