######
# Drupal 8 1.1
# @see https://docs.devwithlando.io/tutorials/drupal8.html
# @see https://github.com/lando/lando/blob/master/examples/drupal8/.lando.yml
# @see https://docs.devwithlando.io/tutorials/setup-additional-services.html
######


# Name
name: APPNAME


# Recipe used
recipe: drupal8
config:
  webroot: .
  php: '7.0'
  via: apache
  database: mariadb:latest
  xdebug: false


# Commands on events
events:
  post-start:
    - appserver: cd $LANDO_MOUNT && composer install
    - appserver: cd $LANDO_WEBROOT && php script.php
    - appserver: cd ~ && echo "alias ll='ls -la'" > .bashrc
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cr -y
    


# Access
proxy:
  appserver:
    - APPNAME.lndo.site
  mailhog:
    - mail.APPNAME.lndo.site
  pma:
    - pma.APPNAME.lndo.site


# Additional services
services:
  appserver:
    composer:
      deployer/deployer: '4.3.0'
  node:
    type: node:latest
    globals:
      gulp-cli: "latest"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  pma:
    type: phpmyadmin


# Additionnal commands line "lando XXX"
tooling:
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
  gulp:
    service: node
  dep:
    service: appserver
    description: "Deploy app with deploy.php"