######
# Wordpress 1.6
# @link https://docs.devwithlando.io/tutorials/wordpress.html
######


# Name
name: APPNAME


# Recipe used
recipe: wordpress
config:
  webroot: .
  php: '7.3'
  via: apache
  database: mariadb
  xdebug: false


# Commands on events
#events:
#  post-start:
#    - appserver: cd ~ && echo "alias ll='ls -la'" > .bashrc


# Access
proxy:
  appserver:
    - APPNAME.lndo.site
  mailhog:
    - mail.APPNAME.lndo.site
  pma:
    - pma.APPNAME.lndo.site


# Additional services
services:
  appserver:
    composer:
      deployer/deployer: '6.*'
  node:
    type: node:11
    globals:
      gulp-cli: "latest"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  pma:
    type: phpmyadmin


# Additionnal commands line "lando XXX"
tooling:
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
  gulp:
    service: node
  dep:
    service: appserver
    description: "Deploy app with deploy.php"